require:
  - standard
  - rubocop-md
  - rubocop-rails
  - rubocop-capybara
  - rubocop-minitest
inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  TargetRailsVersion: 5.2
  Exclude:
    - .idea/**/*
    - node_modules/**/*
    - src/**/*
    - dist/**/*
    - vendor/**/*

Style/FrozenStringLiteralComment:
  Enabled: true

Rails:
  Enabled: true # enable rubocop-rails cops

Rails/OutputSafety:
  Exclude:
    - test/components/previews/**/*